import { Story } from "../types/story";

export const mockStories: Story[] = [
  {
    id: "1",
    title: "Daily Horoscope",
    subtitle: "(No publish date set)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 31, 8:56 PM",
    status: "draft",
    liveFrom: undefined,
    ends: undefined,
  },
  {
    id: "2",
    title: "Daily Horoscope",
    subtitle: "(August 28)",
    pages: ["/assets/images/fencer.png", "/assets/images/fencer.png"],
    lastModified: "Mar 31, 8:41 PM",
    status: "scheduled",
    liveFrom: "Aug 28, 11:15 AM",
    ends: "Jan 7, 9:45 PM",
  },
  {
    id: "3",
    title: "Daily Horoscope",
    subtitle: "(October 10)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 5, 5:11 PM",
    status: "live",
    liveFrom: "Oct 16, 1:30 PM",
    ends: "Jan 12, 9:45 PM",
  },
  {
    id: "4",
    title: "Weekly Wallpapers",
    subtitle: "(June 7)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Jul 2, 9:59 AM",
    status: "past",
    liveFrom: "Jun 2, 8:26 AM",
    ends: "Jul 30, 5:31 AM",
  },
  {
    id: "5",
    title: "Weekly Wallpapers",
    subtitle: "(May 19)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Apr 25, 3:04 PM",
    status: "live",
    liveFrom: "May 19, 4:48 AM",
    ends: "Dec 14, 5:35 PM",
  },
  {
    id: "6",
    title: "News",
    subtitle: "(June 3)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 20, 12:38 PM",
    status: "live",
    liveFrom: "Jun 3, 7:30 AM",
    ends: "Apr 3, 12:58 PM",
  },
];
