import { Status, Story } from "../types/story";

export const mockStories: Story[] = [
  {
    id: "1",
    title: "Daily Horoscope",
    subtitle: "(No publish date set)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 31, 8:56 PM",
    status: Status.Draft,
    liveFrom: undefined,
    ends: undefined,
  },
  {
    id: "2",
    title: "Daily Horoscope",
    subtitle: "(August 28)",
    pages: ["/assets/images/fencer.png", "/assets/images/fencer.png"],
    lastModified: "Mar 31, 8:41 PM",
    status: Status.Scheduled,
    liveFrom: "Aug 28, 11:15 AM",
    ends: "Jan 7, 9:45 PM",
  },
  {
    id: "3",
    title: "Daily Horoscope",
    subtitle: "(October 16)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 5, 5:11 PM",
    status: Status.Live,
    liveFrom: "Oct 16, 1:30 PM",
    ends: "Jan 12, 9:45 PM",
  },
  {
    id: "4",
    title: "Daily Horoscope Daily Horoscope Daily Horoscope Daily Horoscope",
    subtitle: "(November 23)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
      "/assets/images/foci.jpeg",
    ],
    lastModified: "Jul 2, 9:59 AM",
    status: Status.Scheduled,
    liveFrom: "Jun 2, 8:26 AM",
    ends: "Jul 30, 5:31 AM",
  },
  {
    id: "5",
    title: "Weekly Wallpapers",
    subtitle: "(June 2)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Apr 25, 3:04 PM",
    status: Status.Live,
    liveFrom: "May 19, 4:48 AM",
    ends: "Dec 14, 5:35 PM",
  },
  {
    id: "6",
    title: "Weekly Wallpapers",
    subtitle: "(May 19)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 20, 12:38 PM",
    status: Status.Live,
    liveFrom: "Jun 3, 7:30 AM",
    ends: "Apr 3, 12:58 PM",
  },
  {
    id: "7",
    title: "Weekly Wallpapers",
    subtitle: "(May 19)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 20, 12:38 PM",
    status: Status.Live,
    liveFrom: "Jun 3, 7:30 AM",
    ends: "Apr 3, 12:58 PM",
  },
  {
    id: "8",
    title: "Weekly Wallpapers",
    subtitle: "(May 19)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 20, 12:38 PM",
    status: Status.Live,
    liveFrom: "Jun 3, 7:30 AM",
    ends: "Apr 3, 12:58 PM",
  },
  {
    id: "9",
    title: "Weekly Wallpapers",
    subtitle: "(May 19)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 20, 12:38 PM",
    status: Status.Live,
    liveFrom: "Jun 3, 7:30 AM",
    ends: "Apr 3, 12:58 PM",
  },
  {
    id: "10",
    title: "Weekly Wallpapers",
    subtitle: "(May 19)",
    pages: [
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
      "/assets/images/fencer.png",
    ],
    lastModified: "Mar 20, 12:38 PM",
    status: Status.Live,
    liveFrom: "Jun 3, 7:30 AM",
    ends: "Apr 3, 12:58 PM",
  },
];
